routes/admin.php
<?php
Route::group(['middleware' => 'auth','middleware' => 'isadmin'], function (){

    //ADMIN - PAGE

    Route::get('page/create', 'Admin\Page\PageController@create')->name('page.create');
    Route::post('page/create', 'Admin\Page\PageController@store')->name('page.store');
    Route::get('page', 'Admin\Page\PageController@index')->name('page.list');
    Route::get('page/status/{status}', 'Admin\Page\PageController@page_get_status')->name('page.get.status');
    Route::post('page/status', 'Admin\Page\PageController@status')->name('page.status');
    Route::get('page/update/{id}', 'Admin\Page\PageController@show')->name('page.edit');
    Route::post('page/update/{id}', 'Admin\Page\PageController@update')->name('page.update');
    Route::get('page/search', 'Admin\Page\PageController@search')->name('page.search');

    //ADMIN - POST
    Route::get('post/create', 'Admin\Post\PostController@create')->name('post.create');
    Route::post('post/create', 'Admin\Post\PostController@store')->name('post.store');
    Route::get('post', 'Admin\Post\PostController@index')->name('post.index');
    Route::get('post/edit/{post}', 'Admin\Post\PostController@edit')->name('post.edit');
    Route::put('post/edit/{post}', 'Admin\Post\PostController@update')->name('post.update');
    Route::get('post/status/{status}', 'Admin\Post\PostController@post_get_status')->name('post.get.status');
    Route::post('post/status', 'Admin\Post\PostController@status')->name('post.status');
    Route::get('post/search', 'Admin\Post\PostController@search')->name('post.search');

    //ADMIN - POST CAT
    Route::get('post/cat/index', 'Admin\Post\PostCatController@index')->name('post.cat.index');
    Route::get('post/cat/create', 'Admin\Post\PostCatController@create')->name('post.cat.create');
    Route::get('post/cat/edit/{cat}', 'Admin\Post\PostCatController@edit')->name('post.cat.edit');
    Route::put('post/cat/{cat}', 'Admin\Post\PostCatController@update')->name('post.cat.update');
    Route::post('post/cat/create', 'Admin\Post\PostCatController@store')->name('post.cat.store');
    Route::post('post/cat/status', 'Admin\Post\PostCatController@status')->name('post.cat.status');

    ////ADMIN PRODUCT
    Route::get('product/create','Admin\Product\ProductController@create')->name('product.create');
    Route::post('product/create','Admin\Product\ProductController@store')->name('product.store');
    Route::get('product','Admin\Product\ProductController@index')->name('product');
    Route::get('product/status/{status}','Admin\Product\ProductController@product_get_status')->name('product.get.status');
    Route::post('product/status','Admin\Product\ProductController@status')->name('product.status');
    Route::get('product/search','Admin\Product\ProductController@search')->name('product.search');
    Route::get('product/update/{product}','Admin\Product\ProductController@edit')->name('product.edit');
    Route::post('product/update/{product}','Admin\Product\ProductController@update')->name('product.update');


    Route::get('product/cat/create','Admin\Product\ProductCatController@create')->name('product.cat.create');
    Route::get('product/cat','Admin\Product\ProductCatController@index')->name('product.cat');
    Route::get('product/cat/create','Admin\Product\ProductCatController@create')->name('product.cat.create');
    Route::post('product/cat/create','Admin\Product\ProductCatController@store')->name('product.cat.store');
    Route::post('product/cat/status','Admin\Product\ProductCatController@status')->name('product.cat.status');
    Route::get('product/update/cat/{product}','Admin\Product\ProductCatController@edit')->name('product.cat.edit');
    Route::post('product/update/cat/{product_cat}','Admin\Product\ProductCatController@update')->name('product.cat.update');
    //////ADMIN SALES
    Route::get('order','Admin\Cart\OrderController@index')->name('order');
//    Route::get('order/status/{id}','Admin\Cart\OrderController@order_get_status')->name('order.get.status');
    Route::get('order/search','Admin\Cart\OrderController@search')->name('order.search');
    Route::post('status/order','Admin\Cart\OrderController@status_order')->name('status.order');
    Route::get('order/detail/{id}','Admin\Cart\OrderController@order_detail')->name('order.detail');
    Route::get('delete/order/detail/{id}','Admin\Cart\OrderController@delete_order_detail')->name('delete.order_cart');
    Route::get('update/order/detail','Admin\Cart\OrderController@update_order_detail')->name('update.order_cart');
    Route::get('customer','Admin\Cart\CustomerController@index')->name('customer');
    Route::post('customer/delete','Admin\Cart\CustomerController@delete')->name('customer.delete');
    Route::get('customer/search','Admin\Cart\CustomerController@search')->name('customer.search');
    Route::get('bill/{id}','Admin\Cart\OrderController@bill')->name('bill');
    Route::get('delete/order/detail','Admin\Cart\OrderController@delete')->name('delete.order.detail');

//    Route::get('customer/detail.html','Admin\Cart\CustomerController@customer_detail')->name('customer.detail');
    //// ADMIN SLIDER
    Route::get('slider/create','Admin\Slider\SliderController@create')->name('slider.create');
    Route::post('slider/store','Admin\Slider\SliderController@store')->name('slider.store');
    Route::post('slider/status','Admin\Slider\SliderController@status')->name('slider.status');
    Route::get('slider/update/{slider}','Admin\Slider\SliderController@edit')->name('slider.edit');
    Route::post('slider/update/{slider}','Admin\Slider\SliderController@update')->name('slider.update');
    Route::get('slider/search','Admin\Slider\SliderController@search')->name('slider.search');
    Route::get('slider','Admin\Slider\SliderController@index')->name('slider');
    //////ADMIN ACCOUNT
    Route::get('account','Admin\Account\AccountController@index')->name('account');
//    Route::get('account/{account}','Admin\Account\AccountController@list_account')->name('list.account');
    Route::post('account/status','Admin\Account\AccountController@status')->name('account.status');
    Route::get('account/edit/{id}','Admin\Account\AccountController@edit')->name('account.edit');
    Route::post('account/update/{user}','Admin\Account\AccountController@update')->name('account.update');
    Route::get('account/search','Admin\Account\AccountController@search')->name('account.search');
    Route::get('account/password','Admin\Account\AccountController@password')->name('account.password');
    Route::post('account/password/{user}','Admin\Account\AccountController@change_password')->name('account.change.password');
    // ADMIN METHOD DELIVERY
    Route::get('delivery/create','Admin\MethodDelivery\MethodDeliveryController@create')->name('delivery.create');
    Route::post('delivery/create','Admin\MethodDelivery\MethodDeliveryController@store')->name('delivery.store');
    Route::get('delivery','Admin\MethodDelivery\MethodDeliveryController@index')->name('delivery');
    Route::post('delivery/status','Admin\MethodDelivery\MethodDeliveryController@status')->name('delivery.status');
    Route::get('delivery/edit/{id}','Admin\MethodDelivery\MethodDeliveryController@edit')->name('delivery.edit');
    Route::post('delivery/update/{method_delivery}','Admin\MethodDelivery\MethodDeliveryController@update')->name('delivery.update');
    Route::get('delivery/search','Admin\MethodDelivery\MethodDeliveryController@search')->name('delivery.search');

    //////ADMIN MENU TYPE
    Route::get('menu/type','Admin\Menu\MenuTypeController@index')->name('menu.type');
    Route::post('menu/store','Admin\Menu\MenuTypeController@store')->name('menu.store');
    Route::get('menu/edit/{menu_type}','Admin\Menu\MenuTypeController@edit')->name('menu.edit');
    Route::post('menu/update/{menu_type}','Admin\Menu\MenuTypeController@update')->name('menu.update');
    Route::post('menu/status','Admin\Menu\MenuTypeController@status')->name('menu.status');
    // ADMIN MENU ITEM
    Route::get('menu/item','Admin\Menu\MenuItemController@index')->name('menu.item');
    Route::get('menu/item/get_cat','Admin\Menu\MenuItemController@get_cat')->name('menu.item.cat');
    Route::post('menu/item/store','Admin\Menu\MenuItemController@store')->name('menu.item.store');
    Route::post('menu/item/status','Admin\Menu\MenuItemController@status')->name('menu.item.status');
    Route::get('menu/item/edit/{menu_item}','Admin\Menu\MenuItemController@edit')->name('menu.item.edit');
    Route::post('menu/item/update/{menu_item}','Admin\Menu\MenuItemController@update')->name('menu.item.update');
    //EMAIL MENU
    Route::get('email','Admin\Email\Email_customerController@index')->name('email.store.list');
    Route::get('email/search','Admin\Email\Email_customerController@search')->name('email.search');
    Route::post('email/status','Admin\Email\Email_customerController@status')->name('email.status');
    //Nofication
    Route::get('notification','Admin\Notification\NotificationController@list_notification')->name('notification.list');
    Route::get('notification/delete','Admin\Notification\NotificationController@delete')->name('notification.delete');
    //Quote
    Route::get('quote/list','Admin\Quote\QuoteController@index')->name('quote.list');
    Route::get('quote/create','Admin\Quote\QuoteController@create')->name('quote.create');
    Route::post('quote/store','Admin\Quote\QuoteController@store')->name('quote.store');
    Route::get('quote/edit/{id}','Admin\Quote\QuoteController@edit')->name('quote.edit');
    Route::post('quote/update/{quote}','Admin\Quote\QuoteController@update')->name('quote.update');
    Route::post('quote/status','Admin\Quote\QuoteController@status')->name('quote.status');
});

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Str;

Route::group(['prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect']], function()
{

    //DISPLAY HOME
    Route::get('/','Display\Home\HomeController@index');
    Route::get('home.html','Display\Home\HomeController@index')->name('home');
    //DISPLAY ACOUNT
    Route::get('login.html','Auth\LoginController@showLoginForm')->name('login.account');
    Route::post('login','Auth\LoginController@login')->name('login');
    Route::post('logout','Auth\LoginController@logout')->name('logout');
    Route::post('password/email','Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset.html','Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/reset','Auth\ResetPasswordController@reset')->name('request.password');
    Route::get('password/reset/{token}/{email}.html','Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::get('register.html','Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register','Auth\RegisterController@register')->name('register.account');
    Route::get('information/account','Auth\InformationController@account')->name('information.account');
    Route::post('information/update/{user}','Auth\InformationController@update')->name('information.update');
    Route::view('information/update','auth.information_success')->name('information.update.success');

    //Route::get('information/edit','Auth\InformationController@edit')->name('information.edit');
//DISPLAY Hello Mail Customer
//Route::get('verifie/{code}', 'Auth\RegisterController@verifie')->name('mail.verifie');

//DISPLAY PAGE
    Route::get('trang/{slug}','Display\Page\PageController@show')->name('page');
//DISPLAY POST
    Route::get('bai-viet/{category}','Display\Post\PostController@category')->name('post.category');
    Route::get('bai-viet/{category}/{slug}','Display\Post\PostController@index')->name('post.display');
    Route::get('bai-viet/{category}/{slug}/{parent_slug}','Display\Post\PostController@show')->name('post.display.show')->middleware('view.post.count');
//DISPLAY PRODUCT
    Route::get('san-pham/search','Display\Product\ProductController@search')->name('product.search');
    Route::get('san-pham/{category}','Display\Product\ProductController@category')->name('product.category');
    Route::get('san-pham/{category}/{slug}','Display\Product\ProductController@index')->name('product.display');
    Route::get('san-pham/{category}/{slug}/{parent_slug}','Display\Product\ProductController@show')->name('product.display.show')->middleware('view.count');

//DISPLAY CART
    Route::get('gio-hang/add','Display\Cart\CartController@add')->name('cart.add');
    Route::post('gio-hang/store','Display\Cart\CartController@store')->name('cart.store');
    Route::get('gio-hang/detail','Display\Cart\CartController@index')->name('cart.detail');
    Route::get('gio-hang/content_cart','Display\Cart\CartController@content_cart')->name('cart.content_cart');
    Route::get('gio-hang/change_cart','Display\Cart\CartController@change_cart')->name('cart.change_cart');
    Route::post('gio-hang/delete','Display\Cart\CartController@delete')->name('cart.delete');
    Route::get('gio-hang/delivery','Display\Cart\CartController@delivery')->name('cart.delivery');
    Route::post('gio-hang/delivery/get_city','Display\Cart\CartController@get_city')->name('cart.delivery.get_city');
    Route::post('gio-hang/delivery','Display\Cart\CartController@delivery')->name('cart.delivery.change');
    Route::post('gio-hang/add/delivery','Display\Cart\CartController@add_delivery')->name('cart.delivery.add');
    Route::post('gio-hang/update','Display\Cart\CartController@update_qty')->name('cart.update');
    Route::get('gio-hang/confirm','Display\Cart\CartController@confirm')->name('cart.confirm');
    Route::post('gio-hang/confirm/success','Display\Cart\CartController@confirm_success')->name('cart.confirm_success');
    Route::view('gio-hang/confirm/success','display.cart.success_cart')->name('cart.confirm_sc');
    //Add email customer
    Route::post('email/customer/store','Display\Email\Email_customerController@store')->name('email.customer.store')->middleware('throttle:2,1');
    //Search Category -Product
    Route::get('search','Display\Home\HomeController@search')->name('search');
    //Search Category -Post
    Route::get('search/post','Display\Post\PostController@search')->name('search.post');

    Route::get('/email/success',function (){
        return view('auth.passwords.reset_success');
    });

    Route::get('ok',function (){
        cache()->flush();
        return $cache = cache('recent_post');
//        return collect($cache)->take(2);
//        return $cart=Cart::content();
        $chuoi = '1-2-3-4-5-6-7-8-9-10-11-12';
        $kq = '1-2-3-4-5-6, 7-8-9-10-11-12';
        $array = explode('-', $chuoi);
        return collect($array)->chunk(6)->map(function($item){
            return $item->implode('-');
        })->implode(',');
        return App\User::all()->map(function($user){
            return
                ['email' => $user->email,
                'image' => $user->image
            ];
        });
    });
    Route::get('testproduct', function(){
//        $product= new \App\Models\Admin\Product();
//        $p1 = $product->where('id', 2)->first();
        return $p2 = \App\Models\Admin\Product::where(['id' => 2])->first();

        dd($p1, $p2);
    });

    Route::get('cart',function (){
        Cart::add('293ak', 'Product 2', 1, 9.99);
    });
    Route::get('xoa', function(){
//        return Cart::tax();
//        return Cart::count();
//        echo '<pre>';
        return Cart::destroy();
//        foreach (Cart::content() as $item){
//            echo $item->model->image;
//        };
//
//            return array_slice(Cart::content()->toArray(),0,2);
    });
    Route::get('updatcard/{id}', function($id){
       Cart::update($id, 5);

    });
    Route::get('/test123', function(){
        $products =  \App\Models\Admin\Product_cat::find(10)
            ->product
            ->where('id', 44)
            ->first();

           // ->product = ->product()->get() return ve collection
            // ->product() query builder
        // cau nay se query ra tât cả  product  thuộc product_cat id =10 rồi where bằng collection ra product id = 44

        return $products =  \App\Models\Admin\Product_cat::find(10)
            ->product()
            ->where('id', 44)
            ->first();
        // cau nay se query ra chỉ duy nhất product có id=44 thuộc product_cat id =10

        // tóm lại là 1 câu query ra tất và 1 câu qqery ra 1. nên câu thứ 2 sẽ nhanh hơn.
//        product và product() khac gi nhau ?
        return view('welcome', compact($products));
    });

});

app/Models/Admin/Quote.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

class Quote extends Model
{
    protected  $table="quotes";
    protected $fillable=['id','title_vi','title_en','user_id','status'];
    protected $perPage = 8;
    public function user(){
        return $this->belongsTo('App\User','user_id');
    }

    public  function getCreatedAtAttribute($date)
    {
        return Carbon::parse($date)->format('d/m/Y - H:i:s');
    }
    public function getTitleAttribute(){
        if(LaravelLocalization::setLocale()=='vi'){
            return $this->attributes['title_vi'];
        }elseif(LaravelLocalization::setLocale()=='en'){
            return $this->attributes['title_en'];
        }else{
            return false;
        }
    }
}

resources/views/display/post/detail_post.blade.php
@extends('display.index')
@section('content')
    <div id="wrap">
        <!-- Top bar -->
        <!-- Header -->
        <!-- Content -->
        <div id="content">
            <!-- Linking -->
            <div class="linking">
                <div class="container">
                    <ol class="breadcrumb">
                        <li><a href="{{route('home')}}">@lang('display_lang.home')</a></li>
                        <li><a href="{{route('post.category',$check_category->slug)}}">{{$check_category->title}}</a></li>
                        <li><a href="{{route('post.display',[$check_category->slug,$check_parent->slug])}}">{{$check_parent->title}}</a></li>
                        <li><a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$post->slug])}}">{{$post->title}}</a></li>
                    </ol>
                </div>
            </div>

            <!-- Blog -->
            <section class="blog-single padding-top-30 padding-bottom-60">
                <div class="container">
                    <div class="row">
                        <div class="col-md-9">

                            <!-- Blog Post -->
                            <div class="blog-post">
                                <h6>{{$post->title}}</h6>
                                {!! $post->content !!}
                                <!-- Comments -->
                                    <div class="comments">
                                        <div class="fb-comments" data-href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$post->slug])}}" data-numposts="15"></div>
                                        <div id="fb-root"></div>
                                    </div>
                                <!-- ADD comments -->
                            </div>

                        </div>

                        <!-- Side Bar -->
                        <div class="col-md-3">
                            <div class="shop-side-bar">

                                <!-- Search -->
                                <div class="search">
                                    <form action="{{route('search.post')}}" method="GET">
                                        <label>
                                            <input type="text" value="@if(isset($search)) {{$search}} @endif" name="search" placeholder="Tìm kiếm ...">
                                        </label>
                                        <button type="submit"><i class="fa fa-search"></i></button>
                                    </form>
                                </div>
                                <!-- Categories -->
                                {{--<h6>Danh Mục Bài Viết</h6>--}}
                                {{--<div class="checkbox checkbox-primary">--}}
                                    {{--<ul>--}}
                                        {{--@foreach($category_category as $item_category_category)--}}
                                            {{--<li>--}}
                                                {{--<input id="cate1" class="styled" type="checkbox" >--}}
                                                {{--<a href="{{route('post.category',$item_category_category->slug)}}"> {{$item_category_category->title}} </a>--}}
                                            {{--</li>--}}
                                        {{--@endforeach()--}}
                                    {{--</ul>--}}
                                {{--</div>--}}

                                <!-- Recent Posts -->
                                <h6>Bài viết tương tự</h6>
                                <div class="recent-post">
                                    <!-- Recent Posts -->
                                    @foreach($similar_posts as $item_similar_posts)
                                        <div class="media">
                                            <div class="media-left"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_similar_posts->slug])}}"><img class="img-responsive" src="{{asset($item_similar_posts->image)}}" alt=""> </a> </div>
                                            <div class="media-body"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_similar_posts->slug])}}">{{$item_similar_posts->title}}</a> <span><i class="fa fa-bookmark-o"></i> {{$item_similar_posts->created_at}}</span><span style="border: none;"> <i class="fa fa-eye"></i> {{$item_similar_posts->viewer}} </span> </div>
                                        </div>
                                    @endforeach
                                </div>
                                <h6>Bài viết đã xem</h6>
                                <div class="recent-post">
                                    <!-- Recent Posts -->
                                    @foreach($recent_post as $item_recent_post)
                                        <div class="media">
                                            <div class="media-left"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_recent_post->slug])}}"><img class="img-responsive" src="{{asset($item_recent_post->image)}}" alt=""> </a> </div>
                                            <div class="media-body"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_recent_post->slug])}}">{{$item_recent_post->title}}</a> <span><i class="fa fa-bookmark-o"></i> {{$item_recent_post->created_at}}</span><span style="border: none;"> <i class="fa fa-eye"></i> {{$item_recent_post->viewer}} </span> </div>
                                        </div>
                                    @endforeach
                                </div>
                                <!-- Quote of the Day -->
                                <h6>@lang('display_lang.quote')</h6>
                                <div class="quote-day"> <i class="fa fa-quote-left"></i>
                                    <p>
                                        {{$quote->title}}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Clients img -->
        </div>
        <!-- End Content -->
    </div>
@endsection

resources/views/display/post/post.blade.php
@extends('display.index')
@section('content')
    <div id="content">
            <!-- Linking -->
            <div class="linking">
                <div class="container">
                    <ol class="breadcrumb">
                        <li><a href="{{route('home')}}">@lang('display_lang.home')</a></li>
                        <li><a href="{{route('post.category',$check_category->slug)}}">{{$check_category->title}}</a></li>
                        <li><a href="{{route('post.display',[$check_category->slug,$check_parent->slug])}}">{{$check_parent->title}}</a></li>
                    </ol>
                </div>
            </div>
        <!-- Blog -->
        <section class="blog-page padding-top-30 padding-bottom-60">
            <div class="container">
                <div class="row">
                    <div class="col-md-9">
                        @foreach($post as $item)
                            <!-- Blog Post -->
                        <div class="blog-post">
                            <article class="row">
                                <div class="col-xs-7"><a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item->slug])}}"><img class="img-responsive" src="{{asset($item->image)}}" alt="" ></a> </div>
                                <div class="col-xs-5"> <span><i class="fa fa-bookmark-o"></i> {{$item->created_at}} </span> <span><i class="fa fa-eye"></i>{{$item->viewer}} @lang('display_lang.view')</span> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item->slug])}}" class="tittle">{{$item->title}} </a>
                                    <p>{!!$item->description !!}</p>
                                    <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item->slug])}}">Đọc thêm..</a></div>
                            </article>
                        </div>
                        @endforeach
                        <!-- pagination -->
                        {{$post->links('vendor.pagination.pagination')}}
                    </div>

                    <!-- Side Bar -->
                    <div class="col-md-3">
                        <div class="shop-side-bar">
                            <!-- Search -->
                            <div class="search">
                                <form action="{{route('search.post')}}" method="GET">
                                    <label>
                                        <input type="text" name="search" value="@if(isset($search)) {{$search}} @endif" placeholder="Tìm kiếm ...">
                                    </label>
                                    <button type="submit"><i class="fa fa-search"></i></button>
                                </form>
                            </div>
                            <!-- Categories -->
                            {{--<h6>Danh Mục Bài Viết</h6>--}}
                            {{--<div class="checkbox checkbox-primary">--}}
                                {{--<ul>--}}
                                    {{--@foreach($category_category as $item_category_category)--}}
                                        {{--<li>--}}
                                            {{--<input id="cate1" class="styled" type="checkbox" >--}}
                                            {{--<a href="{{route('post.category',$item_category_category->slug)}}">{{$item_category_category->title}} </a>--}}
                                        {{--</li>--}}
                                    {{--@endforeach()--}}
                                {{--</ul>--}}
                            {{--</div>--}}

                            <!-- Recent Posts -->
                            <h6>Bài viết liên quan</h6>
                            <div class="recent-post">
                                <!-- Recent Posts -->
                                @foreach($similar_posts as $item_similar_posts)
                                <div class="media">
                                    <div class="media-left"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_similar_posts->slug])}}"><img class="img-responsive" src="{{asset($item_similar_posts->image)}}" alt=""> </a> </div>
                                    <div class="media-body"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_similar_posts->slug])}}">{{$item_similar_posts->title}}</a> <span><i class="fa fa-bookmark-o"></i> {{$item_similar_posts->created_at}}</span><span  style="border: none;"> <i class="fa fa-eye"></i> {{$item_similar_posts->viewer}} </span> </div>
                                </div>
                                @endforeach
                            </div>
                            <h6>Bài viết đã xem</h6>
                            <div class="recent-post">
                                <!-- Recent Posts -->
                                @foreach($recent_post as $item_recent_post)
                                    <div class="media">
                                        <div class="media-left"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_recent_post->slug])}}"><img class="img-responsive" src="{{asset($item_recent_post->image)}}" alt=""> </a> </div>
                                        <div class="media-body"> <a href="{{route('post.display.show',[$check_category->slug,$check_parent->slug,$item_recent_post->slug])}}">{{$item_recent_post->title}}</a> <span><i class="fa fa-bookmark-o"></i> {{$item_recent_post->created_at}}</span><span  style="border: none;"> <i class="fa fa-eye"></i> {{$item_recent_post->viewer}} </span> </div>
                                    </div>
                                @endforeach
                            </div>
                            <!-- Quote of the Day -->
                            <h6>@lang('display_lang.quote')</h6>
                            <div class="quote-day"> <i class="fa fa-quote-left"></i>
                                <p>
                                    {{$quote->title}}
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection()